export type MockStamp = {
  id: string
  crawl_id: string
  stop_id: string
  cafe_name: string
  user_id: string
  username: string
  avatar_url: string | null
  claimed_at: string
  claim_method: "qr" | "manual" | "redemption"
  claim_lat: number
  claim_lng: number
  cafe_lat: number
  cafe_lng: number
  distance_meters: number
  is_verified: boolean
  verification_note: string | null
}

export type MockUser = {
  id: string
  username: string
  avatar_url: string | null
}

export const MOCK_USERS: MockUser[] = [
  { id: "user-1", username: "marivic", avatar_url: null },
  { id: "user-2", username: "jcruiz", avatar_url: null },
  { id: "user-3", username: "tinabee", avatar_url: null },
  { id: "user-4", username: "admin_override", avatar_url: null },
  { id: "user-5", username: "kyla_m", avatar_url: null },
  { id: "user-6", username: "dio", avatar_url: null },
  { id: "user-7", username: "pam_s", avatar_url: null },
]

export const MOCK_STAMPS: MockStamp[] = [
  {
    id: "stamp-1",
    crawl_id: "crawl-1",
    stop_id: "stop-1",
    cafe_name: "Cafe Georg",
    user_id: "user-1",
    username: "marivic",
    avatar_url: null,
    claimed_at: "2026-07-03T14:23:00+08:00",
    claim_method: "qr",
    claim_lat: 10.3157,
    claim_lng: 123.8854,
    cafe_lat: 10.3157,
    cafe_lng: 123.8855,
    distance_meters: 12,
    is_verified: true,
    verification_note: null,
  },
  {
    id: "stamp-2",
    crawl_id: "crawl-1",
    stop_id: "stop-2",
    cafe_name: "Tamp",
    user_id: "user-2",
    username: "jcruiz",
    avatar_url: null,
    claimed_at: "2026-07-04T09:45:00+08:00",
    claim_method: "qr",
    claim_lat: 10.3182,
    claim_lng: 123.8871,
    cafe_lat: 10.3182,
    cafe_lng: 123.8871,
    distance_meters: 3,
    is_verified: true,
    verification_note: null,
  },
  {
    id: "stamp-3",
    crawl_id: "crawl-1",
    stop_id: "stop-3",
    cafe_name: "Kof",
    user_id: "user-3",
    username: "tinabee",
    avatar_url: null,
    claimed_at: "2026-07-05T16:10:00+08:00",
    claim_method: "qr",
    claim_lat: 10.3201,
    claim_lng: 123.889,
    cafe_lat: 10.3201,
    cafe_lng: 123.8895,
    distance_meters: 45,
    is_verified: true,
    verification_note: null,
  },
  {
    id: "stamp-4",
    crawl_id: "crawl-1",
    stop_id: "stop-4",
    cafe_name: "Common Room",
    user_id: "user-5",
    username: "kyla_m",
    avatar_url: null,
    claimed_at: "2026-07-06T11:30:00+08:00",
    claim_method: "qr",
    claim_lat: 10.3125,
    claim_lng: 123.882,
    cafe_lat: 10.3126,
    cafe_lng: 123.8821,
    distance_meters: 15,
    is_verified: true,
    verification_note: null,
  },
  {
    id: "stamp-5",
    crawl_id: "crawl-1",
    stop_id: "stop-5",
    cafe_name: "Cebu Union",
    user_id: "user-6",
    username: "dio",
    avatar_url: null,
    claimed_at: "2026-07-07T18:50:00+08:00",
    claim_method: "qr",
    claim_lat: 10.308,
    claim_lng: 123.878,
    cafe_lat: 10.3081,
    cafe_lng: 123.878,
    distance_meters: 8,
    is_verified: true,
    verification_note: null,
  },
  {
    id: "stamp-6",
    crawl_id: "crawl-1",
    stop_id: "stop-6",
    cafe_name: "Kuppa",
    user_id: "user-2",
    username: "jcruiz",
    avatar_url: null,
    claimed_at: "2026-07-08T20:15:00+08:00",
    claim_method: "qr",
    claim_lat: 10.33,
    claim_lng: 123.905,
    cafe_lat: 10.3157,
    cafe_lng: 123.8854,
    distance_meters: 312,
    is_verified: true,
    verification_note: null,
  },
  {
    id: "stamp-7",
    crawl_id: "crawl-1",
    stop_id: "stop-1",
    cafe_name: "Cafe Georg",
    user_id: "user-7",
    username: "pam_s",
    avatar_url: null,
    claimed_at: "2026-07-09T07:20:00+08:00",
    claim_method: "qr",
    claim_lat: 10.352,
    claim_lng: 123.91,
    cafe_lat: 10.3157,
    cafe_lng: 123.8854,
    distance_meters: 487,
    is_verified: true,
    verification_note: null,
  },
  {
    id: "stamp-8",
    crawl_id: "crawl-1",
    stop_id: "stop-2",
    cafe_name: "Tamp",
    user_id: "user-4",
    username: "admin_override",
    avatar_url: null,
    claimed_at: "2026-07-10T13:00:00+08:00",
    claim_method: "manual",
    claim_lat: 10.3182,
    claim_lng: 123.8871,
    cafe_lat: 10.3182,
    cafe_lng: 123.8871,
    distance_meters: 0,
    is_verified: true,
    verification_note:
      "QR standee damaged at counter. Owner confirmed visit via DM. Admin: @admin_override",
  },
  {
    id: "stamp-9",
    crawl_id: "crawl-1",
    stop_id: "stop-3",
    cafe_name: "Kof",
    user_id: "user-1",
    username: "marivic",
    avatar_url: null,
    claimed_at: "2026-07-11T10:45:00+08:00",
    claim_method: "redemption",
    claim_lat: 10.3201,
    claim_lng: 123.8892,
    cafe_lat: 10.3201,
    cafe_lng: 123.8895,
    distance_meters: 22,
    is_verified: true,
    verification_note: null,
  },
  {
    id: "stamp-10",
    crawl_id: "crawl-1",
    stop_id: "stop-4",
    cafe_name: "Common Room",
    user_id: "user-3",
    username: "tinabee",
    avatar_url: null,
    claimed_at: "2026-07-12T15:30:00+08:00",
    claim_method: "qr",
    claim_lat: 10.3125,
    claim_lng: 123.882,
    cafe_lat: 10.3125,
    cafe_lng: 123.882,
    distance_meters: 10,
    is_verified: false,
    verification_note:
      "Revoked: GPS coordinates inconsistent with cafe location. Admin: @admin_override",
  },
]
